import './globals.css';
import { Rubik } from 'next/font/google';
import { LenisProvider } from '@/context/lenisContent';
import React from 'react';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <LenisProvider>
        <body className={rubik.className}>{children}</body>
      </LenisProvider>
    </html>
  );
}
